import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const version=String(pkg.version||'').trim();
const versionCode=Number(pkg.versionCode||0);
if(!/^3\.\d+\.\d+$/.test(version))throw new Error('package version must be a 3.x.y RSS version');
if(!Number.isSafeInteger(versionCode)||versionCode<=0)throw new Error('package versionCode must be a positive integer');
const p='android/app/build.gradle';
let s=fs.readFileSync(p,'utf8');
if(!/versionCode\s+\d+/.test(s)||!/versionName\s+"[^"]*"/.test(s))throw new Error('Android version fields not found');
s=s.replace(/versionCode\s+\d+/,`versionCode ${versionCode}`).replace(/versionName\s+"[^"]*"/,`versionName "${version}"`);
fs.writeFileSync(p,s);
console.log('[patch-version] '+version+' ('+versionCode+')');
